[package]
name = "clash_rules"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1"
ipnet = "2"
prefix-trie = "0.6"
radix_trie = "0.2"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_yaml_ng = "0.10.0"


[dev-dependencies]
criterion = "0.5"
bloomfilter = "3.0.1"

[[bench]]
name = "algorithms"
harness = false
